spring:
   datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password: password
   jpa:
      generate-ddl: true
      hibernate:
         ddl-auto: create-drop
      defer-datasource-initialization: true
      show-sql: true
      properties:
         hibernate:
            format_sql: true
            globally_quoted_identifiers: true
kafka:
    bootstrapAddress: localhost:9092
    groupId: 7523

